/**
 * AUTO-GENERATED FILE.
 *
 * This file is regenerated by `npm run generate:client`.
 * Do not edit manually; extend the wrapper class instead.
 */

import {
  ClientViewControllerBase,
  IClientCallableResult,
  IClientRuntime,
} from "../../src/client/runtime.js";
import type {
  ISampleViewData,
  ISampleViewControllerMethodArgs,
  ISampleViewControllerMethodReturn,
} from "../models/sample.js";

export class SampleViewControllerGenerated extends ClientViewControllerBase<
  ISampleViewData
> {
  constructor(runtime: IClientRuntime) {
    super(runtime, "SampleView");
  }


/**
   * Updates the view counter and returns a formatted result message.
   *
   * @param args - Method arguments containing message label and increment amount.
   * @returns Method result containing the formatted message.
   */
  async SampleViewControllerMethod(
    args: ISampleViewControllerMethodArgs
  ): Promise<
    IClientCallableResult<
      ISampleViewControllerMethodReturn,
      ISampleViewData
    >
  > {
    return this.invokeMethod<ISampleViewControllerMethodReturn>("SampleViewControllerMethod", args);
  }
}
