/**
 * AUTO-GENERATED FILE.
 *
 * This file is regenerated by `npm run generate:client`.
 * Do not edit manually; extend the wrapper class instead.
 */

import {
  ClientControllerMethodArgs,
  ClientControllerMethodResult,
  ClientControllerViewData,
  ClientViewControllerBase,
  IClientCallableResult,
  IClientRuntime,
} from "../../src/client/runtime.js";
import type { SampleViewController } from "../server/sample.js";

export class SampleViewControllerGenerated extends ClientViewControllerBase<
  ClientControllerViewData<typeof SampleViewController>
> {
  constructor(runtime: IClientRuntime) {
    super(runtime, "SampleView");
  }


/**
   * Updates the view counter and returns a formatted result message.
   *
   * @param args - Method arguments containing message label and increment amount.
   * @returns Method result containing the formatted message.
   */
  async SampleViewControllerMethod(
    args: ClientControllerMethodArgs<typeof SampleViewController, "SampleViewControllerMethod">
  ): Promise<
    IClientCallableResult<
      ClientControllerMethodResult<typeof SampleViewController, "SampleViewControllerMethod">,
      ClientControllerViewData<typeof SampleViewController>
    >
  > {
    return this.invokeMethod<
      ClientControllerMethodResult<typeof SampleViewController, "SampleViewControllerMethod">
    >("SampleViewControllerMethod", args);
  }
}
